### ISSUE TITLE
"ENOENT: no such file or directory, stat" on symlinks

### ISSUE THREAD

**Issue by pxwise** [AngularClass/resolve-angular-routes#1]
**Overview of the Issue** - when webpack runs on npm start in universal-starter, symlinks throw the following error on my component directories containing symlinks to Gemfiles:

```
Error: ENOENT: no such file or directory, stat '/universal-starter/src/app/components/my-component/Gemfile'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at /universal-starter/wu-universal/node_modules/@angularclass/resolve-angular-routes/index.js:33:17
    at Array.filter (native)
    at resolveNgRoute (/universal-starter/node_modules/@angularclass/resolve-angular-routes/index.js:31:6)
    at /universal-starter/node_modules/@angularclass/resolve-angular-routes/index.js:38:16
    at Array.map (native)
    at resolveNgRoute (/universal-starter/node_modules/@angularclass/resolve-angular-routes/index.js:35:6)
    at /universal-starter/node_modules/@angularclass/resolve-angular-routes/index.js:38:16
    at Array.map (native)
```

**Version** @angularclass/resolve-angular-routes 1.0.9 in angular2-universal 2.0.11

**Motivation for or Use Case** - shared sass / compass config in Gemfiles across components, easiest with symlink ref

**Browsers and Operating System** - OS X El Cpaitan 10.11.6

**Reproduce the Error** - place a symlink in the app directory and run npm start in universal-starter

**Related Issues** - ?

**Suggest a Fix** - detect and ignore symlinks

**Comment by PatrickJS** [comment]
you can remove resolveNgRoute from the 3rd option from ContextReplacementPlugin and avoid using strings for async loading
